services:
  homepage:
    container_name: homepage
    image: ${HOMEPAGE_IMAGE:-ghcr.io/gethomepage/homepage}:${HOMEPAGE_IMAGE_TAG:-latest}
    profiles: ["${HOMEPAGE_PROFILE:-information}"]
    restart: unless-stopped
    networks:
      - external
      - internal
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: false
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    # user: "${PGID:-1000}:${PUID:-1000}"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      UMASK: "000"
      # Image
      DOCKER_HOST: "tcp://socket-proxy:2375"
      HOMEPAGE_ALLOWED_HOSTS: "$DOMAIN"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/app/config"
      - "./logs:/app/config/logs"
      - "./images:/app/public/images"
      # For easy access in widgets.yaml for drive space
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_MUSIC:/data/music:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Information"
      - "homepage.name=Homepage"
      - "homepage.weight=-1"
      - "homepage.icon=mdi-ip-network-outline"
      - "homepage.widgets[0].type=customapi"
      - "homepage.widgets[0].method=GET"
      - "homepage.widgets[0].refreshInterval=60000"
      - "homepage.widgets[0].url=https://api.ipify.org?format=json"
      - "homepage.widgets[0].mappings[0].label=IPv4"
      - "homepage.widgets[0].mappings[0].field=ip"
      - "homepage.widgets[0].mappings[0].format=text"

      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`$DOMAIN`)"
      - "traefik.http.routers.homepage.middlewares=homepage,tinyauth,error-pages"
      - "traefik.http.services.homepage.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.homepage.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.homepage.headers.accessControlAllowOriginList=https://$DOMAIN"
