services:
  chaptarr:
    container_name: chaptarr
    image: ${CHAPTARR_IMAGE:-robertlordhood/chaptarr}:${CHAPTARR_IMAGE_TAG:-latest}
    pull_policy: missing
    profiles: ["${CHAPTARR_PROFILE:-media}"]
    extends:
      file: ../compose.extend.yaml
      service: "pg-${USE_POSTGRES:-false}_vpn-${USE_VPN:-false}"
    restart: unless-stopped
    networks:
      - internal
      - external
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      UMASK: "000"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "./backup:/config/Backups"
      - "./logs:/config/logs"
      - "$PATH_AUDIOBOOKS_SYNC:/data/Audiobooks:ro"
      - "$PATH_BOOKS:/data/Books:ro"
      - "$PATH_DOWNLOADS:/data/Downloads:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Media"
      - "homepage.name=Chaptarr"
      - "homepage.icon=readarr.png"
      - "homepage.href=https://chaptarr.$DOMAIN/"
      - "homepage.description=Audiobooks and Ebooks"
      - "homepage.widget.type=readarr"
      - "homepage.widget.url=http://chaptarr:8789"
      - "homepage.widget.key=${CHAPTARR_API:-}"

      - "traefik.enable=true"
      - "traefik.http.routers.chaptarr.rule=Host(`chaptarr.$DOMAIN`)"
      - "traefik.http.routers.chaptarr.middlewares=chaptarr,tinyauth,error-pages"
      - "traefik.http.services.chaptarr.loadbalancer.server.port=8789"
      - "traefik.http.middlewares.chaptarr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.chaptarr.headers.accessControlAllowOriginList=https://$DOMAIN"

    # healthcheck:
    #   interval: "30s"
    #   timeout: "5s"
    #   retries: 3
    #   start_period: "10s"
    #   test: "wget --no-verbose --tries=1 --spider http://localhost:8789/ || exit 1"
