services:
  beszel:
    container_name: beszel
    image: ${BESZEL_IMAGE:-henrygd/beszel}:${BESZEL_IMAGE_TAG:-latest}
    profiles: ["${BESZEL_PROFILE:-information}"]
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      traefik:
        condition: service_started
        restart: false
      beszel-agent:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      PUID: "${PUID:-1000}"
      PGID: "${PGID:-1000}"
      # Image
      APP_URL: "https://beszel.$DOMAIN/"
      USER_EMAIL: "${BESZEL_USERNAME:-}"
      USER_PASSWORD: "${BESZEL_PASSWORD:-}"
    volumes:
      - "./config:/beszel_data"
      - "./config:/beszel_socket"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Information"
      - "homepage.name=Beszel"
      - "homepage.icon=beszel.png"
      - "homepage.href=https://beszel.$DOMAIN/system/$DOMAIN"
      - "homepage.description=System resource usage"
      - "homepage.widget.type=beszel"
      - "homepage.widget.url=http://beszel:8090"
      - "homepage.widget.version=2"
      - "homepage.widget.systemId=${DOMAIN}"
      - "homepage.widget.username=${BESZEL_USERNAME:-}"
      - "homepage.widget.password=${BESZEL_PASSWORD:-}"

      - "traefik.enable=true"
      - "traefik.http.routers.beszel.rule=Host(`beszel.$DOMAIN`)"
      - "traefik.http.routers.beszel.middlewares=beszel,tinyauth,error-pages"
      - "traefik.http.services.beszel.loadbalancer.server.port=8090"
      - "traefik.http.middlewares.beszel.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.beszel.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "2s"
      test: ["CMD", "/beszel", "health", "--url", "http://localhost:8090"]

  beszel-agent:
    container_name: beszel-agent
    image: ${BESZEL_AGENT_IMAGE:-henrygd/beszel-agent-nvidia}:${BESZEL_AGENT_IMAGE_TAG:-latest}
    profiles: ["${BESZEL_AGENT_PROFILE:-information}"]
    extends:
      file: ../compose.extend.yaml
      service: "gpu-${USE_GPU:-none}"
    restart: unless-stopped
    networks:
      - internal
    depends_on:
      socket-proxy:
        condition: service_healthy
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    environment:
      # Default
      TZ: "${TZ:-Europe/London}"
      # Image
      DOCKER_HOST: "tcp://socket-proxy:2375"
      HUB_URL: "http://beszel:8090"
      LISTEN: "45876"
      TOKEN: "${BESZEL_AGENT_TOKEN:-}"
      KEY: "${BESZEL_AGENT_KEY:-}"
    volumes:
      - "/etc/os-release:/etc/os-release:ro"
      - "./config:/beszel_data"
      - "./config:/beszel_socket:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"
      - "traefik.enable=false"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "2s"
      test: ["CMD", "/agent", "health"]
