services:
  notifiarr:
    container_name: notifiarr
    # YOu must use the "cuda" tag to support Nvidia GPU
    image: ${NOTIFIARR_IMAGE:-ghcr.io/notifiarr/notifiarr}:${NOTIFIARR_IMAGE_TAG:-latest}
    profiles: ["${NOTIFIARR_PROFILE:-information}"]
    extends:
      file: ../compose.extend.yaml
      service: "gpu-${USE_GPU:-none}"
    restart: unless-stopped
    privileged: true
    networks:
      - internal
      - external
    hostname: "notifiarr.$DOMAIN"
    depends_on:
      traefik:
        condition: service_started
        restart: false
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    user: "${PUID:-1000}:${PGID:-1000}"
    environment:
      DN_LIDARR_0_NAME: "lidarr"
      DN_LIDARR_0_URL: "http://lidarr:8686"
      DN_LIDARR_0_API_KEY: "${LIDARR_API:-}"
      DN_PROWLARR_0_NAME: "prowlarr"
      DN_PROWLARR_0_URL: "http://prowlarr:9696"
      DN_PROWLARR_0_API_KEY: "${PROWLARR_API:-}"
      DN_RADARR_0_NAME: "radarr"
      DN_RADARR_0_URL: "http://radarr:7878"
      DN_RADARR_0_API_KEY: "${RADARR_API:-}"
      DN_SONARR_0_NAME: "sonarr"
      DN_SONARR_0_URL: "http://sonarr:8989"
      DN_SONARR_0_API_KEY: "${SONARR_API:-}"
      DN_QBIT_0_NAME: "qbittorrent"
      DN_QBIT_0_URL: "http://qbittorrent:8080"
      DN_SABNZBD_0_NAME: "sabnzbd"
      DN_SABNZBD_0_URL: "http://sabnzbd:8085"
      DN_SABNZBD_0_API_KEY: "${SABNZBD_API:-}"
      DN_PLEX_URL: "https://plex:32400"
      DN_PLEX_TOKEN: "${PLEX_TOKEN:-}"
      DN_TAUTULLI_NAME: "tautulli"
      DN_TAUTULLI_URL: "http://tautulli:8181"
      DN_TAUTULLI_API_KEY: "${TAUTULLI_API:-}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./config:/config"
      - "/var/run/utmp:/var/run/utmp"
      - "/etc/machine-id:/etc/machine-id"
      - "$PATH_MOVIES:/data/movies:ro"
      - "$PATH_MUSIC:/data/music:ro"
      - "$PATH_TV:/data/tv:ro"
    labels:
      - "deunhealth.restart.on.unhealthy=true"

      - "homepage.group=Tools"
      - "homepage.name=Notifiarr"
      - "homepage.icon=notifiarr.png"
      - "homepage.href=https://notifiarr.$DOMAIN/"
      - "homepage.description=System notifications"

      - "traefik.enable=true"
      - "traefik.http.routers.notifiarr.rule=Host(`notifiarr.$DOMAIN`)"
      - "traefik.http.routers.notifiarr.middlewares=notifiarr,tinyauth,error-pages"
      - "traefik.http.services.notifiarr.loadbalancer.server.port=5454"
      - "traefik.http.middlewares.notifiarr.headers.accessControlAllowCredentials=true"
      - "traefik.http.middlewares.notifiarr.headers.accessControlAllowOriginList=https://$DOMAIN"

    healthcheck:
      interval: "30s"
      timeout: "5s"
      retries: 3
      start_period: "10s"
      test: "timeout 1 bash -c 'cat < /dev/null > /dev/tcp/localhost/5454'"
